<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProviderPagesNewTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('provider_pages_new')->delete();
        
        \DB::table('provider_pages_new')->insert(array (
            0 => 
            array (
                'id' => 2317,
                'provider' => 2059,
                'sp_tel' => '02037780035',
                'sp_email' => 'shabnum@embracingage.org.uk',
                'sp_add1' => 'ETNA Community Centre',
                'sp_add2' => '13 Rosslyn Road',
                'sp_add3' => 'Twickenham',
                'sp_add_postcode' => 'TW1 2AR',
                'user_id' => 0,
                'sp_title_1' => 'Volunteer Project Coordinator - Cards for Kindness',
                'sp_title_2' => 'Helping to co-ordinate the cards of kindness being sent to care home residents.',
                'sp_header' => NULL,
                'sp_logo' => '',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2026-01-15 20:51:46',
                'sp_created' => '2026-01-15 20:51:46',
                'sp_live' => 0,
                'sp_status' => 1,
                'sp_website' => 'https://www.embracingage.org.uk/',
                'sp_desc' => 'Liaise with volunteers who are making cards. 
Keep the resident name list up to date. 
Coordinate with care homes to arrange card deliveries and meet residents.
Take photos of residents with their cards (with permission).
Provide regular progress updates to the Richmond Coordinator.
',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'id' => 2316,
                'provider' => 2045,
                'sp_tel' => '',
                'sp_email' => 'del@caiushouse.org',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Digital Talent',
                'sp_title_2' => ' Digital Talent Programme â€“ Tech-Caius hosted by Caius House',
                'sp_header' => NULL,
                'sp_logo' => 'Screenshot_2025-12-01_132957.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-12-01 13:39:47',
                'sp_created' => '2025-12-01 13:39:47',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.caiushouse.org/education',
                'sp_desc' => 'We are looking for 20 young people aged 18 â€“ 24 who are interested in launching their careers in the Digital, Data and Tech sectors. This flexible 8 month programme of support will support you to learn more about routes into these sectors, attend talks by industry experts and visit businesses in London.      
Along the way, you will develop:
- Essential Skills
- Professional Skills
- Gain Career Exposure + Work Experience
- Gain 2 qualifications',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'id' => 2315,
                'provider' => 2045,
                'sp_tel' => '020 3818 6210 ',
                'sp_email' => 'info@caiushouse.org',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Caius House',
                'sp_title_2' => 'A vibrant hub where friendships form and futures take shape',
                'sp_header' => NULL,
                'sp_logo' => 'Screenshot_1111.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-12-01 13:46:19',
                'sp_created' => '2025-12-01 12:26:45',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.caiushouse.org/',
                'sp_desc' => 'Caius House is a welcoming youth centre in Battersea.
It offers music, art, sport and creative programmes for ages 8â€“21.
A safe, inclusive space where young people can grow and explore.
Modern facilities support learning, confidence and community.
Caius House helps every young person discover their potential.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'id' => 2314,
                'provider' => 2050,
                'sp_tel' => '07791 071850',
                'sp_email' => 'ku.oc.daerysaeog@olleh',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Go Easy Read',
                'sp_title_2' => 'Supporting clients to build inclusive communication practices',
                'sp_header' => NULL,
                'sp_logo' => 'Screenshot_2025-11-26_141314.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-11-26 14:19:04',
                'sp_created' => '2025-11-26 14:19:04',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://goeasyread.co.uk',
                'sp_desc' => 'Go Easy Read helps organisations and individuals turn complex documents into accessible, easyâ€‘toâ€‘understand content. They convert reports, leaflets, web pages, forms, policies and more into â€œEasy Readâ€â€”using clear language and simple images to make information understandable for people with learning disabilities, reading difficulties, or limited English. 
They  also offer plainâ€‘language editing, document review, user testing and subtitling',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'id' => 2313,
                'provider' => 2052,
                'sp_tel' => '020 7923 5500',
                'sp_email' => 'enquiries@place2be.org.uk',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Place2Be',
                'sp_title_2' => 'Offering counselling, emotional support and training to help young people',
                'sp_header' => NULL,
                'sp_logo' => 'place2be-strapline-colour.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-11-26 13:22:45',
                'sp_created' => '2025-11-26 13:22:45',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.place2be.org.uk/',
                'sp_desc' => ' Is a UK-wide children and young peopleâ€™s mental health charity working in schools. 
They provide in-school counselling, support services and training for pupils, families and school staff â€” offering one-to-one help, group work, and crisis support. 

Their mission: no child should have to face mental health challenges alone â€” helping children build coping skills, improve wellbeing, and thrive through early intervention.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'id' => 2312,
                'provider' => 2053,
                'sp_tel' => '',
                'sp_email' => 'wandsworthwelcomesrefugees@gmail.com',
                'sp_add1' => 'Wandsworth Welcomes Refugees, c/o Church of St Mar',
                'sp_add2' => 'Balham High Road,',
                'sp_add3' => ' London',
                'sp_add_postcode' => ' SW12 9BS',
                'user_id' => 0,
                'sp_title_1' => 'Wandsworth Welcomes Refugees',
                'sp_title_2' => 'volunteer-led charity that supports asylum seekers and refugees',
                'sp_header' => NULL,
                'sp_logo' => '6606da605195ac4f7c8faab9_wandsworth-welcomes-refugees-logo.p',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-11-26 13:01:30',
                'sp_created' => '2025-11-26 12:58:40',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.wandsworthwelcomesrefugees.org',
                'sp_desc' => 'Wandsworth Welcomes Refugees is a volunteer-led charity building a borough where asylum seekers and refugees are welcomed with dignity and compassion.
They partner with local organisations to create inclusive â€œplaces of sanctuaryâ€ across Wandsworth.
Their support network connects people to essential services, donated items and community opportunities.
Through strong local partnerships, they promote social inclusion and equal access for all.
WWR works to ensure every newcomer can rebuild their li',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'id' => 2311,
                'provider' => 2058,
                'sp_tel' => '',
                'sp_email' => 'gemma@act-up.co.uk',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'living-communities',
                'sp_title_2' => 'build community, foster connection, and empower those often left out',
                'sp_header' => NULL,
                'sp_logo' => '',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-11-26 12:39:12',
                'sp_created' => '2025-11-26 12:39:12',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://living-communities.co.uk/about/',
                'sp_desc' => 'Living Communities CIC is a community-interest group that brings creative workshops and arts-based activities to people often overlooked by mainstream programmes. They focus on supporting underserved or underrepresented groups â€” from isolated older adults, asylum-seeking families, and neurodiverse individuals, to those facing mental-health challenges or economic hardship, and people from non-Caucasian backgrounds.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'id' => 2310,
                'provider' => 2080,
                'sp_tel' => '02086731129',
                'sp_email' => 'robert.hayes@gll.org',
                'sp_add1' => 'Balham Library ',
                'sp_add2' => '16 Ramsden Road',
                'sp_add3' => 'London',
                'sp_add_postcode' => 'SW12 8QY',
                'user_id' => 0,
            'sp_title_1' => 'Forget-Me-Not Group (Dementia Journey & Friends)',
                'sp_title_2' => 'A friendly meeting place for people with memory problems and their Carer\\\'s',
                'sp_header' => NULL,
                'sp_logo' => 'Fotget-Me-Not_Group__White__2.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-11-25 10:51:33',
                'sp_created' => '2025-11-10 10:37:47',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => '',
                'sp_desc' => 'A friendly meeting place for people with memory problems, their carer\\\'s, friends and family. Chat and share experiences and information in a safe, friendly and supportive environment. Join in activities like games, singing, music and art.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'id' => 2309,
                'provider' => 2061,
                'sp_tel' => ' 020 8321 6300 ',
                'sp_email' => 'talk@themulberrycentre.co.uk',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'The Mulberry Centre',
                'sp_title_2' => ' Free support, information, and wellbeing services',
                'sp_header' => NULL,
                'sp_logo' => '',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-10-20 11:46:44',
                'sp_created' => '2025-10-20 11:46:44',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://themulberrycentre.co.uk/',
                'sp_desc' => 'The Mulberry Centre provides free, compassionate support and information for anyone affected by cancer â€” including patients, carers, family members and the bereaved. Based in West London, this independent charity offers counselling, complementary therapies, wellbeing classes, creative activities and practical help, all tailored to individual needs and grounded in inclusive, caring values.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'id' => 2308,
                'provider' => 2066,
                'sp_tel' => '',
                'sp_email' => 'estateartsw15@gmail.com',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Estate Art',
                'sp_title_2' => 'Promoting wellbeing and connection through creativity',
                'sp_header' => NULL,
                'sp_logo' => 'Screenshot_2025-10-20_105128.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-10-20 11:03:11',
                'sp_created' => '2025-10-20 11:03:11',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.estateart.co.uk/about',
                'sp_desc' => 'Is an awardâ€‘winning communityâ€‘driven notâ€‘forâ€‘profit organisation based in Roehampton, dedicated to empowering residents and fostering community cohesion through creative, inclusive arts projects. From supporting mental and physical wellbeing during the Covidâ€‘19 pandemic to pioneering healthâ€‘champion initiatives with local NHS partners, Estateâ€¯Art uses culture, collaboration and social care to connect and strengthen their community.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'id' => 2307,
                'provider' => 2068,
                'sp_tel' => '',
                'sp_email' => 'grace@oscarspathwayltd.com.mx',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'Oscar\\\'s Pathway',
                'sp_title_2' => 'Activities focusing on life skills, engagement, creativity and community trips',
                'sp_header' => NULL,
                'sp_logo' => 'art3.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-10-20 10:37:08',
                'sp_created' => '2025-10-20 10:37:08',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.instagram.com/oscarspathway?igsh=eDh0bDJsY3loc2Nz&utm_source=qr',
                'sp_desc' => 'Oscar\\\'s Pathway LTD is a specialist day provision for young people and adults with a diagnosis of autism and a severe learning disability ages 16-45 in South West London. Our young people also have significant communication and sensory needs.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'id' => 2306,
                'provider' => 2067,
                'sp_tel' => '',
                'sp_email' => 'theartycraftycrescentclub@gmail.com',
                'sp_add1' => '',
                'sp_add2' => '',
                'sp_add3' => '',
                'sp_add_postcode' => '',
                'user_id' => 0,
                'sp_title_1' => 'The Arty-Crafty Crescent Club CIC',
                'sp_title_2' => 'Spirit of collaboration and creativity.',
                'sp_header' => NULL,
                'sp_logo' => 'art1.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-10-20 10:01:13',
                'sp_created' => '2025-10-20 10:01:13',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.instagram.com/the_artycrafty_crescent_club',
                'sp_desc' => 'Is a welcoming, inclusive space where people of all ages and backgrounds come together to explore creativity through hands-on arts and crafts inspired by diverse culture while building community, sharing skills, and promoting sustainability in a fun and meaningful way.
Through collaborative projects, cultural storytelling, accessible workshops, the club fosters a strong sense of belonging, encourages intergenerational connection, and empowers individuals to a richer, more connected Wandsworth',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'id' => 2305,
                'provider' => 2075,
                'sp_tel' => '',
                'sp_email' => 'wecare@wecarecampaign.org.uk',
                'sp_add1' => '4 Riverside Cottages ',
                'sp_add2' => '4 Riverside ',
                'sp_add3' => 'Canterbury ',
                'sp_add_postcode' => 'CT4 7JR',
                'user_id' => 0,
                'sp_title_1' => 'We Care Campaign',
                'sp_title_2' => 'Empowering unpaid carers to feel visible and valued.',
                'sp_header' => NULL,
                'sp_logo' => 'Picture1_2.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-10-14 17:13:16',
                'sp_created' => '2025-10-14 17:13:16',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://wecarecampaign.org.uk/',
                'sp_desc' => 'Is a grassroots, carer-led movement in the UK dedicated to elevating the voices of unpaid carers. The campaign has tirelessly advocated for recognition, respect, and support for carers. 
Driven by lived experience, We Care Campaign works to:
â€¢	Ensure unpaid carers are heard, valued, and visibly represented. 
â€¢	Secure better financial support, access to breaks, and stronger social care provision. 
â€¢	Amplify carersâ€™ stories in order to influence policy, public perception, and cultural change
',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'id' => 2304,
                'provider' => 2076,
                'sp_tel' => ' 02031438878',
                'sp_email' => 'westlondon@visiting-angels.co.uk',
                'sp_add1' => 'Boundary House Business Centre',
                'sp_add2' => 'Boston Road',
                'sp_add3' => 'Brentford',
                'sp_add_postcode' => ' W7 2QE',
                'user_id' => 0,
                'sp_title_1' => 'Visiting Angels Home Care',
                'sp_title_2' => 'Your Home Care Needs Are Personal To Us.',
                'sp_header' => NULL,
                'sp_logo' => 'visiting-angels-logo-retina.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-24 13:19:41',
                'sp_created' => '2025-09-24 13:19:41',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.visiting-angels.co.uk/westlondon/',
                'sp_desc' => 'At Visiting Angels, our home care services and support are tailored to your needs so you can continue to live independently and happily in the comfort of your own home. 

From hourly visits to 24 hour live in care, our award-winning and longstanding care business provides tailored support locally in and around West & South West London. ',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'id' => 2303,
                'provider' => 2076,
                'sp_tel' => ' 02031438878',
                'sp_email' => 'westlondon@visiting-angels.co.uk',
                'sp_add1' => 'Boundary House Business Centre',
                'sp_add2' => 'Boston Road',
                'sp_add3' => 'Brentford',
                'sp_add_postcode' => ' W7 2QE',
                'user_id' => 0,
                'sp_title_1' => 'Visiting Angels Home Care',
                'sp_title_2' => 'Your Home Care Needs Are Personal To Us.',
                'sp_header' => NULL,
                'sp_logo' => 'visiting-angels-logo-retina.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-24 13:19:41',
                'sp_created' => '2025-09-24 13:19:41',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.visiting-angels.co.uk/westlondon/',
                'sp_desc' => 'At Visiting Angels, our home care services and support are tailored to your needs so you can continue to live independently and happily in the comfort of your own home. 

From hourly visits to 24 hour live in care, our award-winning and longstanding care business provides tailored support locally in and around West & South West London. ',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'id' => 2302,
                'provider' => 2078,
                'sp_tel' => '07956261130',
                'sp_email' => 'info@fightingknifecrime.london',
                'sp_add1' => '9 Little St Leonards,',
                'sp_add2' => '',
                'sp_add3' => ' London',
                'sp_add_postcode' => 'SW14 7LT',
                'user_id' => 0,
                'sp_title_1' => 'Fighting Knife Crime London',
                'sp_title_2' => 'Our purpose is to address the causes and  effects of knife crime',
                'sp_header' => NULL,
                'sp_logo' => '6051ad24a28428164abb878a_KNIFE_CRIME_-_LOGO.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-24 13:06:00',
                'sp_created' => '2025-09-24 13:06:00',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'http://www.fightingknifecrime.london',
                'sp_desc' => 'is a dynamic online platform dedicated to empowering young people across Greater London. Through up-to-date news, a regular magazine, videos, research, and a growing directory of support organisations, it fosters collaboration among those working to change young lives. Supported by professionals from youth work, mental health, education, business, policing, and the arts, its mission is to combat social exclusion, promote confidence, and celebrate the positive impact of young people.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'id' => 2301,
                'provider' => 2081,
                'sp_tel' => '02083263702',
                'sp_email' => 'jacinta.richardson@reed.com',
                'sp_add1' => '2nd Floor Unex Tower',
                'sp_add2' => '5 station Street',
                'sp_add3' => 'London',
                'sp_add_postcode' => ' E15 1DA',
                'user_id' => 0,
                'sp_title_1' => 'Reed Community Care Recruitment',
                'sp_title_2' => 'Care provides 24/7 for adults, children, and families with complex care needs',
                'sp_header' => NULL,
                'sp_logo' => '',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-24 11:57:13',
                'sp_created' => '2025-09-24 11:57:13',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.reed.com/offices/recruitment-agencies-in-london',
                'sp_desc' => 'Reed Community Care Recruitment is committed to providing compassionate, personâ€‘centred support to vulnerable adults, children, young people, and familiesâ€”right in their own communities. As a registered Care Quality Commission provider, Reed offers a full spectrum of community care services including support for learning disabilities and autism, complex clinical care, mental health, outreach and respite, and specialised care for children and young people.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'id' => 2300,
                'provider' => 2086,
                'sp_tel' => '07807398181',
                'sp_email' => 'wandsworth@bagsoftaste.org',
                'sp_add1' => 'Run remotely for wandsworth residents',
                'sp_add2' => 'Wandsworth borough',
                'sp_add3' => 'Wandsworth',
                'sp_add_postcode' => 'SW11 3RA',
                'user_id' => 0,
                'sp_title_1' => 'Bags of Taste free cooking programme',
                'sp_title_2' => 'Eat better on a budget - FREE home mentored cooking programme',
                'sp_header' => NULL,
                'sp_logo' => 'bags_of_test_2.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-01 12:45:00',
                'sp_created' => '2025-09-01 12:34:39',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://bagsoftaste.org/',
            'sp_desc' => 'The Bags of Taste course is completely home based - we deliver a FREE bag of ingredients to your door and give you personal help and videos by WhatsApp or phone, while you cook three delicious FREE meals (7 portions in total), in your own time! You will improve your skills, wellbeing and finances.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'id' => 2299,
                'provider' => 2086,
                'sp_tel' => '07807398181',
                'sp_email' => 'wandsworth@bagsoftaste.org',
                'sp_add1' => 'Run remotely for wandsworth residents',
                'sp_add2' => 'Wandsworth borough',
                'sp_add3' => 'Wandsworth',
                'sp_add_postcode' => 'SW11 3RA',
                'user_id' => 0,
                'sp_title_1' => 'Bags of Taste ',
                'sp_title_2' => 'Working with people in poverty to improve their diets',
                'sp_header' => NULL,
                'sp_logo' => 'bags_of_test.jpg',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-09-01 12:43:14',
                'sp_created' => '2025-08-19 01:30:01',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://bagsoftaste.org/',
                'sp_desc' => 'We work with some of the most vulnerable in the UK to support them to improve their diets for the long term.
People living with multiple challenges and disadvantages often make poor and expensive food choices leading to nutritional inequalities which affect their finances, health, mental health and families. The causes of this are often misunderstood. We are experts in these social determinants of health and our programmes help participants overcome these barriers to a better diet and life.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'id' => 2298,
                'provider' => 2084,
                'sp_tel' => '0300 003 2324',
                'sp_email' => 'info@relationships-service.org.uk',
                'sp_add1' => 'test',
                'sp_add2' => 'test',
                'sp_add3' => 'test',
                'sp_add_postcode' => 'xx12 1pa',
                'user_id' => 0,
                'sp_title_1' => 'The Relationships Service ',
                'sp_title_2' => 'Counselling & Family Mediation',
                'sp_header' => NULL,
                'sp_logo' => 'the-relationship-service-logo.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-08-15 19:11:07',
                'sp_created' => '2025-08-15 19:09:46',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.relationships-service.org.uk/',
                'sp_desc' => 'The Relationships Service is a long-established BACP-accredited charity offering affordable, high-quality counselling and mediation services since we were known as Marriage Guidance Counsel in 1946.
ðŸ¤ Counselling & Mediation Support
If you\\\'re experiencing relationship difficulties, you donâ€™t need to suffer in silence. Our focused, compassionate counsellors can help you explore the best path forwardâ€”whether that means rebuilding your relationship or separating with clarity and support.

',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'id' => 2297,
                'provider' => 2079,
                'sp_tel' => '020 30896590',
                'sp_email' => 'contact@integrity-care.co.uk',
                'sp_add1' => 'Unit 18 G/F Hillgate Place',
                'sp_add2' => '18-20, Balham Hill',
                'sp_add3' => 'Balham',
                'sp_add_postcode' => 'SW12 9ER',
                'user_id' => 0,
                'sp_title_1' => 'Integrity Healthcare Solutions Ltd. T/A Integrity Care',
                'sp_title_2' => 'Home care services provider London',
                'sp_header' => NULL,
                'sp_logo' => '',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-07-09 12:42:32',
                'sp_created' => '2025-06-03 12:45:38',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.integrity-care.co.uk',
                'sp_desc' => 'Integrity Care is a growing provider of domiciliary care services in London and the surrounding areas. We offer a wide range of services to help people live independently and safely in their own homes.
Our services are high-quality, person-centred domiciliary care for adults and children.',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'id' => 2296,
                'provider' => 2077,
                'sp_tel' => '0777 554 1848',
                'sp_email' => 'elnaef@royaltrinityhospice.london',
                'sp_add1' => 'Royal Trinity Hospice ',
                'sp_add2' => '30 Clapham Common North Side, London ',
                'sp_add3' => 'Wandsworth',
                'sp_add_postcode' => 'SW4 0RN',
                'user_id' => 0,
                'sp_title_1' => 'Compassionate Neighbours - Tackling loneliness in last years of life',
                'sp_title_2' => 'Matching local people to enable weekly social visits',
                'sp_header' => NULL,
                'sp_logo' => 'in_Central_and_South_West_London.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2025-04-17 22:25:46',
                'sp_created' => '2025-04-03 14:46:14',
                'sp_live' => 0,
                'sp_status' => 4,
                'sp_website' => 'https://www.royaltrinityhospice.london/compassionate-neighbours',
            'sp_desc' => 'Compassionate Neighbours matches local people with those who are in the last years of life due to age (85+) or illness (palliative/life-limiting/terminal conditions). 
They then visit those referred on a weekly basis for a social visit to improve social connection and decrease loneliness.',
            'sp_distance' => 0,
            'archive' => 0,
            'created_at' => '0000-00-00 00:00:00',
            'updated_at' => '0000-00-00 00:00:00',
        ),
        22 => 
        array (
            'id' => 2295,
            'provider' => 2074,
            'sp_tel' => '020 8339 5100',
            'sp_email' => 'surbiton.enquiries@starandgarter.org',
            'sp_add1' => 'Upper Brighton Road',
            'sp_add2' => '',
            'sp_add3' => ' Surbiton',
            'sp_add_postcode' => ' KT6 6JY',
            'user_id' => 0,
            'sp_title_1' => 'Royal Star & Garter Care with Courage',
            'sp_title_2' => 'To provide an outstanding range of quality care and therapies ',
            'sp_header' => NULL,
            'sp_logo' => 'carehome_4567_-_Copy.png',
            'sp_gm_lat' => NULL,
            'sp_gm_long' => NULL,
            'sp_publish' => 0,
            'sp_publish_date' => '2025-02-24 20:17:14',
            'sp_created' => '2025-02-24 20:17:14',
            'sp_live' => 0,
            'sp_status' => 4,
            'sp_website' => 'https://starandgarter.org/',
            'sp_desc' => 'We provide care for veterans and their partners, who live with disability or dementia, in three state-of-the-art Homes and we have launched new services reaching out into the community, including Day Care, Lunch Clubs and a Telephone Friendship Service.',
            'sp_distance' => 0,
            'archive' => 0,
            'created_at' => '0000-00-00 00:00:00',
            'updated_at' => '0000-00-00 00:00:00',
        ),
        23 => 
        array (
            'id' => 2294,
            'provider' => 2073,
            'sp_tel' => '01702 870190',
            'sp_email' => '',
            'sp_add1' => 'Grand Connaught Rooms',
            'sp_add2' => ' 61 - 65 Great Queen Street',
            'sp_add3' => ' London ',
            'sp_add_postcode' => 'WC2B 5DA',
            'user_id' => 0,
            'sp_title_1' => 'From Menstruation To Menopause',
            'sp_title_2' => 'Celebrating every chapter of women\\\'s health',
            'sp_header' => NULL,
            'sp_logo' => 'manap.png',
            'sp_gm_lat' => NULL,
            'sp_gm_long' => NULL,
            'sp_publish' => 0,
            'sp_publish_date' => '2025-02-24 18:25:30',
            'sp_created' => '2025-02-24 18:20:43',
            'sp_live' => 0,
            'sp_status' => 4,
            'sp_website' => 'https://www.pauselive.com/',
            'sp_desc' => 'Get head-to-toe advice from leading experts that you deserve... and take back control of y Including help with the following: â€¢ Hot Flushe
â€¢ Sleep Solutions â€¢ Brain Fog â€¢ Mental Health
â€¢ Intimate Health â€¢ Weight Management
â€¢ (plus the other 75+ symptoms!)',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'id' => 2293,
                'provider' => 2059,
                'sp_tel' => '02037780035',
                'sp_email' => 'shabnum@embracingage.org.uk',
                'sp_add1' => 'ETNA Community Centre',
                'sp_add2' => '13 Rosslyn Road',
                'sp_add3' => 'Twickenham',
                'sp_add_postcode' => 'TW1 2AR',
                'user_id' => 0,
                'sp_title_1' => 'Intergenerational Schools Liaison Volunteer',
                'sp_title_2' => 'There are wonderful benefits to connecting children and care home residents',
                'sp_header' => NULL,
                'sp_logo' => 'Embracing_Age_logo_png_3.png',
                'sp_gm_lat' => NULL,
                'sp_gm_long' => NULL,
                'sp_publish' => 0,
                'sp_publish_date' => '2026-01-15 20:47:26',
                'sp_created' => '2025-01-30 11:51:16',
                'sp_live' => 0,
                'sp_status' => 1,
                'sp_website' => 'https://www.embracingage.org.uk/',
                'sp_desc' => 'Liaising with schools 
Planning intergenerational projects, such as exchanging pictures
or letters between residents and children, and encouraging schools
to adopt their local care home, arrange visits to residents who have no relatives.
Recruiting a team of volunteers to help',
                'sp_distance' => 0,
                'archive' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}