<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceCatsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_cats')->delete();
        
        \DB::table('service_cats')->insert(array (
            0 => 
            array (
                'service_cat_id' => 1,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => '-',
                'service_cat_desc' => '',
                'service_cat_image' => '',
                'service_cat_icon' => NULL,
                'service_cat_count' => 0,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'service_cat_id' => 31,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Care and support',
                'service_cat_desc' => 'Care and support',
                'service_cat_image' => 'care.jpg',
                'service_cat_icon' => 'mdi-account',
                'service_cat_count' => 76,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'service_cat_id' => 131,
                'service_cat_level' => 1,
                'service_cat_parent' => 115,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Counselling and talking therapies',
                'service_cat_desc' => 'Counselling, Support and Self-Help',
                'service_cat_image' => 'category_images/puzzle_in_pieces.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 160,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'service_cat_id' => 36,
                'service_cat_level' => 1,
                'service_cat_parent' => 31,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Living independently at home',
                'service_cat_desc' => 'Independent living',
                'service_cat_image' => 'category_images/Living_independently.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 57,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'service_cat_id' => 41,
                'service_cat_level' => 1,
                'service_cat_parent' => 31,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Care at home',
                'service_cat_desc' => 'Care at home',
                'service_cat_image' => 'category_images/real_estate_bubble.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 36,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'service_cat_id' => 42,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Health and wellbeing',
                'service_cat_desc' => 'Health and wellbeing',
                'service_cat_image' => 'health.jpg',
                'service_cat_icon' => 'mdi-hospital',
                'service_cat_count' => 646,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'service_cat_id' => 44,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Keeping healthy',
                'service_cat_desc' => 'Keeping healthy',
                'service_cat_image' => 'category_images/boy_with_milk_moustaches.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 174,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'service_cat_id' => 45,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Hospitals',
                'service_cat_desc' => 'Hospitals',
                'service_cat_image' => 'category_images/hospitals.JPG',
                'service_cat_icon' => NULL,
                'service_cat_count' => 35,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'service_cat_id' => 46,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Doctors, dentists and other local services',
                'service_cat_desc' => 'Doctors, dentists and other local services',
                'service_cat_image' => 'category_images/medical_instruments_icon.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 136,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'service_cat_id' => 47,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Physiotherapy and rehabilitation',
                'service_cat_desc' => 'Physiotherapy and rehabilitation',
                'service_cat_image' => 'category_images/physiotherapy.JPG',
                'service_cat_icon' => NULL,
                'service_cat_count' => 29,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'service_cat_id' => 48,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Pharmacists ',
                'service_cat_desc' => 'Pharmacists ',
                'service_cat_image' => 'category_images/pharmacies.JPG',
                'service_cat_icon' => NULL,
                'service_cat_count' => 65,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'service_cat_id' => 50,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Specific health conditions',
                'service_cat_desc' => 'Support with health conditions',
                'service_cat_image' => 'category_images/Asthma.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 260,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'service_cat_id' => 51,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Housing and care homes',
                'service_cat_desc' => 'Housing and care homes',
                'service_cat_image' => 'housing.jpg',
                'service_cat_icon' => 'mdi-home-outline',
                'service_cat_count' => 97,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'service_cat_id' => 52,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Housing advice',
                'service_cat_desc' => 'Housing advice',
                'service_cat_image' => 'category_images/housingadvice.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 54,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'service_cat_id' => 53,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Sheltered, supported & extra care housing',
                'service_cat_desc' => 'Sheltered, Supported and Extra Care Housing',
                'service_cat_image' => 'category_images/shelteredhousingordayactivities.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 31,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'service_cat_id' => 54,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Residential and nursing homes',
                'service_cat_desc' => 'Residential and nursing homes',
                'service_cat_image' => 'category_images/summer_garden.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 19,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'service_cat_id' => 55,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Repairs and adaptations',
                'service_cat_desc' => 'Repairs and adaptations',
                'service_cat_image' => 'category_images/toy_tools.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 16,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'service_cat_id' => 56,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Tenancy support and benefits',
                'service_cat_desc' => 'Tenancy support and benefits',
                'service_cat_image' => 'category_images/benefits.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 14,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'service_cat_id' => 57,
                'service_cat_level' => 1,
                'service_cat_parent' => 51,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Other housing issues',
                'service_cat_desc' => 'Other housing issues',
                'service_cat_image' => 'category_images/housing_care_homes.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 25,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'service_cat_id' => 168,
                'service_cat_level' => 1,
                'service_cat_parent' => 112,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Legal Advice',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/legal_advice.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 35,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'service_cat_id' => 59,
                'service_cat_level' => 1,
                'service_cat_parent' => 58,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Money and debt advice',
                'service_cat_desc' => 'Money advice and information',
                'service_cat_image' => 'category_images/save_spend_invest.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 42,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'service_cat_id' => 62,
                'service_cat_level' => 1,
                'service_cat_parent' => 58,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Benefits advice',
                'service_cat_desc' => 'Benefits and other support',
                'service_cat_image' => 'category_images/benefits.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 70,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            22 => 
            array (
                'service_cat_id' => 64,
                'service_cat_level' => 1,
                'service_cat_parent' => 58,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Managing someone else\'\'s money',
                'service_cat_desc' => 'Managing money on someone else\'s behalf',
                'service_cat_image' => 'category_images/financial_examination.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 12,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            23 => 
            array (
                'service_cat_id' => 66,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Keeping safe and secure',
                'service_cat_desc' => 'Keeping safe and secure',
                'service_cat_image' => 'safe.jpg',
                'service_cat_icon' => 'mdi-lock',
                'service_cat_count' => 84,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'service_cat_id' => 67,
                'service_cat_level' => 1,
                'service_cat_parent' => 66,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Safeguarding adults from abuse',
                'service_cat_desc' => 'Safeguarding adults from abuse',
                'service_cat_image' => 'category_images/safeguarding.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 26,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            25 => 
            array (
                'service_cat_id' => 186,
                'service_cat_level' => 1,
                'service_cat_parent' => 31,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Support planning',
                'service_cat_desc' => NULL,
                'service_cat_image' => '',
                'service_cat_icon' => NULL,
                'service_cat_count' => 29,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            26 => 
            array (
                'service_cat_id' => 69,
                'service_cat_level' => 1,
                'service_cat_parent' => 66,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Personal and home safety',
                'service_cat_desc' => 'Keeping safe from crime',
                'service_cat_image' => 'category_images/Home_Safety.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 46,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            27 => 
            array (
                'service_cat_id' => 70,
                'service_cat_level' => 1,
                'service_cat_parent' => 66,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Domestic violence',
                'service_cat_desc' => 'Domestic violence',
                'service_cat_image' => 'category_images/domestic_violence.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 49,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            28 => 
            array (
                'service_cat_id' => 72,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Travel and getting about',
                'service_cat_desc' => 'Travel and getting about',
                'service_cat_image' => 'travel.jpg',
                'service_cat_icon' => 'mdi-train',
                'service_cat_count' => 126,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            29 => 
            array (
                'service_cat_id' => 73,
                'service_cat_level' => 1,
                'service_cat_parent' => 72,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Transport help',
                'service_cat_desc' => 'Transport options',
                'service_cat_image' => 'Transport_Help.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 22,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            30 => 
            array (
                'service_cat_id' => 74,
                'service_cat_level' => 1,
                'service_cat_parent' => 72,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Shopping services',
                'service_cat_desc' => 'Shopping transport services',
                'service_cat_image' => 'category_images/shoppinghelp.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 12,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            31 => 
            array (
                'service_cat_id' => 75,
                'service_cat_level' => 1,
                'service_cat_parent' => 72,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Wheelchairs and walking supports',
                'service_cat_desc' => 'Wheelchairs and walking supports',
                'service_cat_image' => 'Wheelchairs_and_walking_supports.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 10,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            32 => 
            array (
                'service_cat_id' => 76,
                'service_cat_level' => 1,
                'service_cat_parent' => 72,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Holidays ',
                'service_cat_desc' => 'Holidays ',
                'service_cat_image' => 'category_images/vacation_icons.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 59,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            33 => 
            array (
                'service_cat_id' => 78,
                'service_cat_level' => 1,
                'service_cat_parent' => 72,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Getting out and about',
                'service_cat_desc' => 'Getting out and about',
                'service_cat_image' => 'category_images/travelgettingoutandabout.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 60,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            34 => 
            array (
                'service_cat_id' => 79,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Leisure and activities',
                'service_cat_desc' => 'Things to do / Leisure and activities',
                'service_cat_image' => 'activities.jpg',
                'service_cat_icon' => 'mdi-swim',
                'service_cat_count' => 412,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            35 => 
            array (
                'service_cat_id' => 80,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Arts and culture',
                'service_cat_desc' => 'Arts and culture',
                'service_cat_image' => 'category_images/mentalhealthorarts.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 89,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            36 => 
            array (
                'service_cat_id' => 81,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Sports and fitness',
                'service_cat_desc' => 'Sports and fitness',
                'service_cat_image' => 'category_images/Sport__Fitness.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 87,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            37 => 
            array (
                'service_cat_id' => 82,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Activities and things to do',
                'service_cat_desc' => 'Activities and things to do',
                'service_cat_image' => 'category_images/table_football.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 254,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            38 => 
            array (
                'service_cat_id' => 83,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Day centres and social clubs',
                'service_cat_desc' => 'Day centres and clubs',
                'service_cat_image' => 'category_images/multitude_of_clovers.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 133,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            39 => 
            array (
                'service_cat_id' => 85,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Libraries',
                'service_cat_desc' => 'Libraries',
                'service_cat_image' => 'category_images/york_gardens_library.JPG',
                'service_cat_icon' => NULL,
                'service_cat_count' => 37,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            40 => 
            array (
                'service_cat_id' => 86,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Parks',
                'service_cat_desc' => 'Parks',
                'service_cat_image' => 'category_images/st_georges_park.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 14,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            41 => 
            array (
                'service_cat_id' => 87,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Adult and Community Learning',
                'service_cat_desc' => 'Adult and Community Learning',
                'service_cat_image' => 'category_images/adultlearning.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 152,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            42 => 
            array (
                'service_cat_id' => 88,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Community and getting involved',
                'service_cat_desc' => 'Community and getting involved',
                'service_cat_image' => 'community.jpg',
                'service_cat_icon' => 'mdi-account-group',
                'service_cat_count' => 436,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            43 => 
            array (
                'service_cat_id' => 89,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Community centres',
                'service_cat_desc' => 'Community groups and centres',
                'service_cat_image' => 'category_images/communitycentre.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 167,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            44 => 
            array (
                'service_cat_id' => 171,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Befriending',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/helping_hand.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 151,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            45 => 
            array (
                'service_cat_id' => 169,
                'service_cat_level' => 1,
                'service_cat_parent' => 115,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Self-help groups',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/3D_team_circle.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 246,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            46 => 
            array (
                'service_cat_id' => 91,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Getting involved ',
                'service_cat_desc' => 'Getting involved in the local community',
                'service_cat_image' => 'category_images/worker.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 166,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            47 => 
            array (
                'service_cat_id' => 92,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Volunteering',
                'service_cat_desc' => 'Helping others â€“ volunteering',
                'service_cat_image' => 'category_images/crowds.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 143,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            48 => 
            array (
                'service_cat_id' => 93,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Faith groups',
                'service_cat_desc' => 'Faiths and faiths groups',
                'service_cat_image' => 'category_images/faith_community.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 103,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            49 => 
            array (
                'service_cat_id' => 94,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Education, training & work',
                'service_cat_desc' => 'Working and learning',
                'service_cat_image' => 'education.jpg',
                'service_cat_icon' => 'mdi-school-outline',
                'service_cat_count' => 247,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            50 => 
            array (
                'service_cat_id' => 95,
                'service_cat_level' => 1,
                'service_cat_parent' => 94,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Work and careers',
                'service_cat_desc' => 'Work and careers',
                'service_cat_image' => 'category_images/business_people_taking_oath.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 73,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            51 => 
            array (
                'service_cat_id' => 96,
                'service_cat_level' => 1,
                'service_cat_parent' => 94,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Education and courses',
                'service_cat_desc' => 'Education and courses',
                'service_cat_image' => 'category_images/african_school.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 177,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            52 => 
            array (
                'service_cat_id' => 100,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Caring for someone',
                'service_cat_desc' => 'Caring for / looking after someone',
                'service_cat_image' => 'caring.jpg',
                'service_cat_icon' => 'mdi-account-multiple',
                'service_cat_count' => 150,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            53 => 
            array (
                'service_cat_id' => 101,
                'service_cat_level' => 1,
                'service_cat_parent' => 100,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Support for carers',
                'service_cat_desc' => 'Support for you as a carer',
                'service_cat_image' => 'category_images/raising_help.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 126,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            54 => 
            array (
                'service_cat_id' => 103,
                'service_cat_level' => 1,
                'service_cat_parent' => 100,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Breaks and respite from caring',
                'service_cat_desc' => 'Breaks and respite from caring',
                'service_cat_image' => 'category_images/woman_drinking_tea.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 64,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            55 => 
            array (
                'service_cat_id' => 104,
                'service_cat_level' => 1,
                'service_cat_parent' => 100,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Money and legal matters',
                'service_cat_desc' => 'Money and legal matters for carers',
                'service_cat_image' => 'category_images/financial_examination.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 29,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            56 => 
            array (
                'service_cat_id' => 195,
                'service_cat_level' => 1,
                'service_cat_parent' => 94,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Schools',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'learningschool.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 43,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            57 => 
            array (
                'service_cat_id' => 196,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Funders',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/money_and_plant.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 14,
                'service_cat_page' => 0,
                'created_at' => '2019-04-06 10:40:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            58 => 
            array (
                'service_cat_id' => 170,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Play schemes and activities',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/kids_club.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 129,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            59 => 
            array (
                'service_cat_id' => 112,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Advice, Information & Advocacy',
                'service_cat_desc' => 'Advice, Information and Advocacy',
                'service_cat_image' => 'advice.jpg',
                'service_cat_icon' => 'mdi-information-slab-box-outline',
                'service_cat_count' => 261,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            60 => 
            array (
                'service_cat_id' => 113,
                'service_cat_level' => 1,
                'service_cat_parent' => 112,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Independant Living',
                'service_cat_desc' => 'Independent living ',
                'service_cat_image' => 'category_images/labirinth.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 247,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            61 => 
            array (
                'service_cat_id' => 115,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Counselling',
                'service_cat_desc' => 'Counselling, Support and Self-Help',
                'service_cat_image' => 'counselling.jpg',
                'service_cat_icon' => 'mdi-chat',
                'service_cat_count' => 332,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            62 => 
            array (
                'service_cat_id' => 167,
                'service_cat_level' => 1,
                'service_cat_parent' => 112,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Advocacy',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/Advocacy.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 51,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            63 => 
            array (
                'service_cat_id' => 58,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Benefits and money',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'benefits.jpg',
                'service_cat_icon' => 'mdi-currency-gbp',
                'service_cat_count' => 92,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            64 => 
            array (
                'service_cat_id' => 181,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Addictions',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/addiction.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 54,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            65 => 
            array (
                'service_cat_id' => 182,
                'service_cat_level' => 1,
                'service_cat_parent' => 94,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Nurseries and childcare',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/kids_club.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 67,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            66 => 
            array (
                'service_cat_id' => 180,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Sexual health and pregnancy',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/sexual_health.JPG',
                'service_cat_icon' => NULL,
                'service_cat_count' => 89,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            67 => 
            array (
                'service_cat_id' => 183,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Domestic violence',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'category_images/domestic_violence.jpg',
                'service_cat_icon' => NULL,
                'service_cat_count' => 31,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            68 => 
            array (
                'service_cat_id' => 185,
                'service_cat_level' => 1,
                'service_cat_parent' => 31,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Care support brokerage',
                'service_cat_desc' => NULL,
                'service_cat_image' => '',
                'service_cat_icon' => NULL,
                'service_cat_count' => 14,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            69 => 
            array (
                'service_cat_id' => 200,
                'service_cat_level' => 1,
                'service_cat_parent' => 1,
                'service_cat_has_child' => 1,
                'service_cat_name' => 'Self-Help Groups',
                'service_cat_desc' => NULL,
                'service_cat_image' => 'counselling.jpg',
                'service_cat_icon' => 'mdi-help',
                'service_cat_count' => 273,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            70 => 
            array (
                'service_cat_id' => 1006,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Mental Health',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 46,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            71 => 
            array (
                'service_cat_id' => 1007,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Addictions',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 28,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            72 => 
            array (
                'service_cat_id' => 1008,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Cancer',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 33,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            73 => 
            array (
                'service_cat_id' => 1009,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Alternative Therapies ',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 30,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            74 => 
            array (
                'service_cat_id' => 1010,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Cemeteries and Crematoriums',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 5,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            75 => 
            array (
                'service_cat_id' => 1011,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Charity Shops',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 9,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            76 => 
            array (
                'service_cat_id' => 1012,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Mental health',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 52,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            77 => 
            array (
                'service_cat_id' => 1013,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Carers ',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 55,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            78 => 
            array (
                'service_cat_id' => 1014,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Other',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 190,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            79 => 
            array (
                'service_cat_id' => 1015,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Self-management courses',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 10,
                'service_cat_page' => 0,
                'created_at' => '2019-04-06 10:41:27',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            80 => 
            array (
                'service_cat_id' => 1016,
                'service_cat_level' => 1,
                'service_cat_parent' => 200,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Self-management courses',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 15,
                'service_cat_page' => 0,
                'created_at' => '2019-04-06 10:41:34',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            81 => 
            array (
                'service_cat_id' => 1017,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Visual or hearing impairment',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 30,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            82 => 
            array (
                'service_cat_id' => 1018,
                'service_cat_level' => 1,
                'service_cat_parent' => 88,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Fundraising',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 3,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            83 => 
            array (
                'service_cat_id' => 1033,
                'service_cat_level' => 1,
                'service_cat_parent' => 42,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Loss and bereavement',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 9,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            84 => 
            array (
                'service_cat_id' => 1032,
                'service_cat_level' => 1,
                'service_cat_parent' => 79,
                'service_cat_has_child' => 0,
                'service_cat_name' => 'Theatre and performance',
                'service_cat_desc' => NULL,
                'service_cat_image' => NULL,
                'service_cat_icon' => NULL,
                'service_cat_count' => 24,
                'service_cat_page' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}